logging:
  level:
    com:
      example:
        mgr: debug
    org:
      springframework:
        security: debug


#配置数据源
spring:
  datasource:
    url: jdbc:mysql:loadbalance://192.168.0.111:3306,192.168.0.112:3306,192.168.0.113:3306/test_db?serverTimezone=Asia/Shanghai&roundRobinLoadBalance=true&failOverReadOnly=false&tcpRcvBuf=1024000&loadBalanceStrategy=bestResponseTime&loadBalanceBlacklistTimeout=300000&loadBalancePingTimeout=1000&selfDestructOnPingMaxOperations=200&queryTimeoutKillsConnection=true&loadBalanceValidateConnectionOnSwapServer=true&connectTimeout=1000
    username: root
    druid:
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个配置会将执行的sql打印出来，在开发或测试的时候可以用